apiVersion: v1
kind: Secret
data:
  username: YXBw
  password: YXBwLXBhc3N3b3Jk
metadata:
  name: app-secret
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  annotations:
    linkerd.io/inject: enabled
spec:
  instances: 3
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret

  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
