name: pb_cli
description: CLI for Postgres Backend
version: 0.0.1-alpha.10

executables:
  pb:

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  pb_server: 0.0.1-alpha.10
  dart_style: ^2.3.6
  code_builder: ^4.10.0
  io: ^1.0.4
  checked_yaml: ^2.0.3
  json_annotation: ^4.9.0
  string_validator: ^1.0.2
  pubspec_parse: ^1.2.3
  enum_to_string: ^2.0.1
  petitparser: ^6.0.2
  fast_immutable_collections: ^10.2.3
  decimal: ^2.3.3
  build_version: ^2.1.1
  pub_semver: ^2.1.4

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1