name: pb_server
description: Postgres-Backend Server Library
version: 0.0.1-alpha.2

environment:
  sdk: ^3.1.4

dependencies:
  protobuf: ^3.1.0
  dart_jsonwebtoken: ^2.13.0
  grpc: ^3.2.4
  sodium: ^2.3.0
  random_string: ^2.3.1
  path: ^1.9.0
  enum_to_string: ^2.0.1
  args: ^2.4.2
  logging: ^1.2.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  async: ^2.11.0
  postgres: ^3.1.2


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
