name: pb_converter
description: CLI for Postgres Backend
version: 0.0.1-alpha.10

executables:
  pb:

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  postgres: ^3.2.1
  protobuf: ^3.1.0
  io: ^1.0.4
  decimal: ^3.0.2
  fast_immutable_collections: ^10.2.4
  fixnum: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  test: ^1.25.7
  pubspec_generator: ^4.0.0
