import 'package:pub_semver/pub_semver.dart';
import 'package:pubspec_parse/pubspec_parse.dart';

import '../pg/directive.dart' as d;
import '../pg/directive.dart';
import '../pubspec.yaml.g.dart' as p;
import '../pubspec_client.yaml.g.dart' as pc;
import 'utils.dart';

enum DependencySource {
  client,
  server,
}

Future<void> generatePubspecs() async {
  for (final target in d.Target.all) {
    _dartPubspec(target);
    if (!target.serverOnly) _flutterPubspec(target);
    print('Data models generated for @${target.name}');
  }
}

_dartPubspec(Target target) {
  final name = target.name + '_server';
  final description =
      'Server library generated by Postgres Backend CLI (v. ${p.Pubspec.version.canonical})';
  final environment = _environment('sdk');
  final dependencies = _dependency('pb_server', DependencySource.server);
  final ps = Pubspec(name,
      description: description,
      environment: environment,
      dependencies: dependencies);
  _add(LibraryType.server, target, ps);
}

Map<String, VersionConstraint> _environment(String name) =>
    {name: VersionConstraint.parse(p.Pubspec.environment[name]!)};

Map<String, Dependency> _dependency(String package, DependencySource source) =>
    {
      package: HostedDependency(
          version: VersionConstraint.parse(source == DependencySource.server
              ? p.Pubspec.dependencies[package].toString()
              : pc.Pubspec.dependencies[package].toString()))
    };

_flutterPubspec(Target target) {
  final name = target.name + '_client';
  final description =
      'Client library generated by Postgres Backend CLI (v. ${p.Pubspec.version.canonical})';
  final environment = _environment('sdk');
  final dependencies = _dependency('pb_client', DependencySource.client);
  final ps = Pubspec(name,
      description: description,
      environment: environment,
      dependencies: dependencies);
  _add(LibraryType.server, target, ps);
}

_add(LibraryType libraryType, d.Target target, Pubspec ps) => GeneratedFile.add(
    libraryType, target, ['pubspec'], FileType.yaml, ps.toString());
